name = "cloudflare-worker-tailscale-monitor"
account_id = "<your-account-id>"
main = "src/index.js"

compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = false
preview_urls = false

[triggers]
crons = ["*/5 * * * *"]

[env.prod]
name = "cloudflare-worker-tailscale-monitor-prod"
routes = [
	{ pattern = "cloudflareworkertailscalemonitorprod.example.com", custom_domain = true }
]
kv_namespaces = [
    { binding = "TAILSCALE_NODE_STATUS_KV", preview_id = "<>", id = "<>" },
    { binding = "TAILSCALE_OAUTH_TOKEN_CACHE_KV", preview_id = "<>", id = "<>" }
]

[env.prod.observability]
enabled = true
head_sampling_rate = 1

[env.dev]
name = "cloudflare-worker-tailscale-monitor-dev"
routes = [
	{ pattern = "cloudflareworkertailscalemonitordev.example.com", custom_domain = true }
]
kv_namespaces = [
    { binding = "TAILSCALE_NODE_STATUS_KV", preview_id = "<>", id = "<>" },
    { binding = "TAILSCALE_OAUTH_TOKEN_CACHE_KV", preview_id = "<>", id = "<>" }
]

[env.dev.observability]
enabled = true
head_sampling_rate = 1
